# Generated by Django 3.1.7 on 2021-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_auto_20210314_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='term/images'),
        ),
    ]
